### PR TITLE
Adding guides from Sumana

### PR DESCRIPTION
**Pull request by RichardLitt**
Thank you!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Waiting on image touch-up from memo.

**Review by ocdtrekkie — APPROVED** [review]
I didn't inspect the entire PR line-by-line, but I read some choice topics of interest here, and I think there's a ton of good content here.

**Comment by BenJam** [comment]
FYI GitBoook is set as the primary so this hasn't actually been pulled into the docs...

**Comment by poohlaga** [comment]
thanks. gave a heads up to @RichardLitt and he's gonna fix

**Comment by RichardLitt** [comment]
Working on it. Was confused how Gitbook works, as it says "synced", but I guess that doesn't talk about the source of truth.

**Pull request merged**
